### ISSUE TITLE
Error in chargify code : Start tag expected, '<' not found

### ISSUE THREAD

**Issue by adyc** [abraham/chargify#4]
Hello,

I have used the abraham chargify code along with the Chargify-Php-Client library. I also placed the correct api_key and the subdomain of chargify account. But while running "products.php", it gives the following errors - 

---

Warning:  SimpleXMLElement::__construct() [simplexmlelement.--construct]: Entity: line 1: parser error : Start tag expected, '<' not found in D:\xampp\htdocs\aditya\chargify_source_codes\abraham-chargify\Chargify-PHP-Client\lib\ChargifyConnector.php on line 262

Warning:  SimpleXMLElement::__construct() [simplexmlelement.--construct]:   in D:\xampp\htdocs\aditya\chargify_source_codes\abraham-chargify\Chargify-PHP-Client\lib\ChargifyConnector.php on line 262

Warning:  SimpleXMLElement::__construct() [simplexmlelement.--construct]:  ^ in D:\xampp\htdocs\aditya\chargify_source_codes\abraham-chargify\Chargify-PHP-Client\lib\ChargifyConnector.php on line 262

Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in D:\xampp\htdocs\aditya\chargify_source_codes\abraham-chargify\Chargify-PHP-Client\lib\ChargifyConnector.php:262
Stack trace:
#0 D:\xampp\htdocs\aditya\chargify_source_codes\abraham-chargify\Chargify-PHP-Client\lib\ChargifyConnector.php(262): SimpleXMLElement->__construct(' ')
#1 D:\xampp\htdocs\aditya\chargify_source_codes\abraham-chargify\Chargify-PHP-Client\lib\ChargifyProduct.php(56): ChargifyConnector->getAllProducts()
#2 D:\xampp\htdocs\aditya\chargify_source_codes\abraham-chargify\products.php(24): ChargifyProduct->getAllProducts()
#3 {main}

  thrown in D:\xampp\htdocs\aditya\chargify_source_codes\abraham-chargify\Chargify-PHP-Client\lib\ChargifyConnector.php on line 262

---

Currently, the chargify account is on test mode. Could you please help out and let me know what could have caused this error and if there is a fix for it ?

Thanks,
Ady

**Comment by lumikha** [comment]
Any update about this?
